name: Python Linting

on:
  pull_request:
  push:
    branches: ["main" ]

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  linting-check:
    name: Linting check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install types-PyYAML types-requests

      - name: setup virtual display to test tkinter gui
        uses: coactions/setup-xvfb@v1
        with:
          run: npm test

      - name: Check python format
        run: |
          sh ./scripts/check.sh
